config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'flats#index'
  resources :users
  resources :flats do
    resources :bookings, only: [:create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :customer, class_name: 'User', foreign_key: :customer_id
  belongs_to :flat
  has_one :owner, through: :flat

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  geocoded_by :location
  
  validates :description, presence: true
  validates :price_per_night, presence: true
  validates :name, presence: true
  validates :location, presence: true
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model

  pg_search_scope :search_by_location,
                  against: [ :location ],
                  using: {
                    tsearch: { prefix: true }
                  }
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :flats, foreign_key: :owner_id, dependent: :destroy
  has_many :bookings, foreign_key: :customer_id, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_flat, only: %i[create]

  def show
    @booking = Booking.find(booking_params)
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.flat = @flat
    @booking.customer = current_user

    authorize @booking

    if @booking.save
      redirect_to user_path(current_user)
    else
      render "flats/show", status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :flat_id)
  end

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    # raise
    if params[:search_query].present?
      @flats = policy_scope(Flat).search_by_location(params[:search_query])
      # @flats = Flat.where(location: params[:query])
      @markers = @flats.geocoded.map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude
        }
      end
    else
      @flats = policy_scope(Flat)
      @markers = @flats.geocoded.map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude
        }
      end
    end
  end

  def show
    @flat = Flat.find(params[:id])
    @booking = Booking.new
    authorize @flat
    @markers = [{
      lat: @flat.latitude,
      lng: @flat.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: {flat: @flat})
    }]
  end

  def new
    @flat = Flat.new
    authorize @flat
  end

  def create
    @flat = Flat.new(flat_params)
    authorize @flat
    @flat.owner = current_user
    @flat.save!
    redirect_to flat_path(@flat)
  end

  def edit
    @flat = Flat.find(params[:id])
    authorize @flat
  end

  def update
    @flat = Flat.find(params[:id])
    authorize @flat
    @flat.update(flat_params)
    redirect_to flat_path(@flat.id)
  end

  private

  def flat_params
    params.require(:flat).permit(:description, :price_per_night, :name, :location, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<p></p>
<p>ALL booking(s)</p>

<div class="cards-container">
<% @bookings.each do |booking| %>
  <div class="card-product">
    <% if booking.flat.photo.attached?%>
      <%= cl_image_tag booking.flat.photo.key, class: "card-product-infos" %>
      <% else %>
      <%= image_tag "https://t3.ftcdn.net/jpg/04/62/93/66/360_F_462936689_BpEEcxfgMuYPfTaIAOC1tCDurmsno7Sp.jpg" %>
    <% end %>
  <div class="card-product-infos">
    <h2><%= booking.flat.name %> at <%= booking.flat.location %></h2>
    <p><%= booking.customer.name %></p>
    <p><strong>From </strong><%= booking.start_date %><strong> to </strong><%= booking.end_date %></p></p>
    </div>
  </div>
  <%end%>
<div>

app/views/bookings/new.html.erb
<h1>New booking</h1>
<%= simple_form_for [@flat, @booking] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit "Make booking", class: "btn btn-primary" %>
<% end %>

app/views/bookings/show.html.erb
<p>bookings#show</p>

app/views/flats/_info_window.html.erb
<h2><%= @flat.name %></h2>
<p><%= @flat.location %></p>

app/views/flats/edit.html.erb
<div class="mb-5 p-5"><%= simple_form_for @flat do |f| %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :name %>
    <%= f.input :location %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Update", { class: "submit-btn" } %>
  <% end %></div>

app/views/flats/index.html.erb
<!-- Display flats -->
<%# <%= render "shared/search" %>
<div class="flats-cards-container">
  <div class="card-container">
    <% @flats.each do |flat| %>
      <div class="card">
        <% if flat.photo.attached? %>
          <%= cl_image_tag flat.photo.key, class: "card-img-top", :cloud_name => 'dcakea82q' %>
        <%else%>
          No photo
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= link_to flat.name, flat_path(flat.id) %></h5>
          <p class="card-text"><%= flat.location %></p>
        </div>
      </div>
  <% end %>
  </div>
</div>
<%# <h4>Where you’ll be<h4> %>
<%# <div style="width: 100%; height: 400px;" %>
<%# data-controller="map" %>
<%# data-map-markers-value="<%= @markers.to_json " %>
<%# data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] "></div> %>
<%# <p><strong><%= flat.location <strong></p> %>
<%# <p>There are attractions and public facilities you can be enjoyed nearby such as:</p> %>
<%# </div> %>
<%# <% end %>
<%# </div> %>

app/views/flats/new.html.erb
<div class="d-flex justify-content-center form-container mt-5">
  <%= simple_form_for @flat do |f| %>

    <div class="step active">
      <p id="qn-title"> 1. Let's begin. First, let's give your house a name.</p>
      <p id="qn-subtitle"> Short names work best. Have fun with it - you can always change it later.</p>

      <div class="form-group">
        <%= f.input :name %>
      </div>

      <button type="button" class="next-btn">Next</button>
    </div>

    <div class="step">
      <p id="qn-title"> 2. Describe your house in detail. Share what makes it special.</p>
      <p id="qn-subtitle"> Check out some of our featured homes to find inspiration.</p>

      <div class="form-group">
        <%= f.input :description %>
      </div>

      <button type="button" class="previous-btn">Prev</button>
      <button type="button" class="next-btn">Next</button>
    </div>

    <div class="step">
      <p id="qn-title"> 3. What's the location of your house.</p>
      <p id="qn-subtitle"> No worries - your address is only shared with guests after they made a reservation.</p>

      <div class="form-group">
        <%= f.input :location %>
      </div>

        <button type="button" class="previous-btn">Prev</button>
        <button type="button" class="next-btn">Next</button>
    </div>




    <div class="step">
      <p id="qn-title"> 4. Make your place stand out. Upload a photo of your house.</p>
      <p id="qn-subtitle"> A picture says a thousand words.</p>

      <div class="form-group">
        <%= f.input :photo, as: :file %>
      </div>

      <button type="button" class="previous-btn">Prev</button>
      <button type="button" class="next-btn">Next</button>
    </div>

    <div class="step">
      <p id="qn-title"> 5. Now, set your price. Give it a daily rate.</p>
      <p id="qn-subtitle"> A more reasonable price attracts more views.</p>

      <div class="form-group">
        <%= f.input :price_per_night %>
      </div>

      <button type="button" class="previous-btn">Prev</button>
      <%= f.submit "Submit", class: "submit-btn" %>

  <% end %>
</div>

app/views/flats/show.html.erb
<%# fs-6 d-flex text-center center %>
<h2 class="mt-2 mb-2 fw-bold"><%= @flat.name %></h2>
<!-- summary of flat -->
<div class="d-flex justify-content-between fs-6">
  <div>
    <i class="fa-solid fa-star me-1"></i>
    <span class="me-2"> <%= (rand()*10).round(2) %> </span>
    <span class="me-2"><u> <%= (rand(100))%> reviews </u></span>
    <span><u> <%= @flat.location%></u></span>
    <% if policy(@flat).edit? %>
      <span><u> <%= link_to "Edit", edit_flat_path(@flat.id) %></u></span>
    <%end%>
  </div>
  <div>
    <i class="fa-solid fa-up-right-from-square"></i> <span class="me-2"><u>Share</u></span>
    <i class="fa-solid fa-heart"></i> <span><u>Save</u></span>
  </div>
</div>
<!-- Display image -->
<% if @flat.photo.attached? %>
  <%= cl_image_tag @flat.photo.key, class: "flat-banner"%>
<%else%>
  No photo
<% end %>
<!-- Flat description-->
<%# flex-box %>
<div class="container">
  <div class="row">
    <div class="col-8 p-0">
      <h2>
        Hosted by <span class="logo fw-bold"><%= @flat.owner.name %></span>
      </h2>
      <p class="fs-5">
        <%= (rand(5)+1) %> guests •
        <%= (rand(5)+1) %> bedrooms •
        <%= (rand(5)+1) %> beds •
        <%= (rand(5)+1) %> bathrooms
      </p>
      <hr style="width: 88%;">
      <p class="fs-5"><%= @flat.description %></p>
    </div>
    <div class="col-4 p-0">
      <div class="p-2">
        <div class="booking p-3">
          <h2>$<%= @flat.price_per_night %> SGD per night </h2>
          <%= simple_form_for [@flat, @booking] do |f| %>
            <%= f.input :start_date, as: :date, html5: true %>
            <%= f.input :end_date, as: :date, html5: true %>
            <p class="mt-2">You will be charged <strong>immediately</strong></p>
            <%= f.submit "Reserve", class: "btn booking-button fs-4 rounded-4 btn-sm", id: "form-button" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div>
  <h2 class="fs-4">Where you'll be</h2>
  <div style="width: 100%; height: 400px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  <p class="fs-5 bold my-4"><%= @flat.location %></p>
  <p>Within walking distance from the condominium there is a Family mart, car and bike rental, a laundry, a cafe, a ceramic bakery shop, a large shooting gallery, and massage parlors.</p>
  <p class="bold">Show more</p>
</div>
<%# <%= render "shared/search" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marketplace</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer p-1">
  <div class="d-flex justify-content-between">
    <div class="w-25 p-1">
      <h3>Supports</h3>
      <ul class = "list-unstyled">
        <li><a href="#">Help Centre</a></li>
        <li><a href="#">AirCover</a></li>
        <li><a href="#">Supporting people with disabilities</a></li>
        <%# <li><a href="#">Cancellation options</a></li>
        <li><a href="#">Our COVID-19 Response</a></li>
        <li><a href="#">Report a neighbourhood concern</a></li> %>
      </ul>
    </div>
    <div class="w-25 p-1">
      <h3>Community</h3>
      <ul  class = "list-unstyled">
        <li><a href="#">Airbnb.org: disaster relief housing</a></li>
        <li><a href="#">Combating discrimination</a></li>
      </ul>
    </div>
    <div class="w-25 p-1">
      <h3>Hosting</h3>
      <ul class="list-unstyled">
        <li><a href="#">Airbnb your home</a></li>
        <%# <li><a href="#">AirCover for Hosts</a></li>
        <li><a href="#">Explore hosting resources</a></li> %>
        <%# <li><a href="#">Visit our community forum</a></li>
        <li><a href="#">How to host responsibly</a></li>
      </ul> %>
    </div>
    <div class="w-25 p-1">
      <h3>Airbnb</h3>
      <ul class="list-unstyled">
        <li><a href="#">Newsroom</a></li>
        <%# <li><a href="#">Learn about new features</a></li> %>
        <li><a href="#">Letter from our founders</a></li>
        <%# <li><a href="#">Careers</a></li>
        <li><a href="#">Investors</a></li> %>
      </ul>
    </div>
  </div>
  <div class="mt-1 d-flex justify-content-between">
    <ul class="list-unstyled d-flex">
      <li><a href="#" class="mx-1">© 2023 Airbnb, Inc</a></li>
      <li>·</li>
      <li><a href="#" class="mx-1">Privacy</a></li>
      <li>·</li>
      <li><a href="#" class="mx-1">Terms</a></li>
      <li>·</li>
      <li><a href="#" class="mx-1">Sitemap</a></li>
      <li>·</li>
    </ul>
    <ul class="logo list-unstyled d-flex justify-content-between">
      <li class="icon"><i class="fa-solid fa-globe"></i></li>
      <li><a href="#" class="mx-1">$ SGD</a></li>
      <li><a href="#" class="mx-1">English(SG)</a></li>
      <li><a href="#"><i class="mx-2 fab fa-instagram fa-xl"></i></a></li>
      <li><a href="#"><i class="mx-2 fab fa-facebook fa-xl"></i></a></li>
      <li><a href="#"><i class="mx-2 fab fa-twitter fa-xl"></i></a></li>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon border-top border-bottom">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <i class="fa-brands fa-airbnb logo fs-1"></i>
      <h3 class="logo-title"> fakebnb</h3>
    <% end %>
      <%# <h6 class="logo-subtitle">(we will take your money)</h6> %>
    <%# <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
      <%= render "shared/search" %>

    <div class="dropdown">
      <button class="btn profile-btn border rounded-pill" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="fa-solid fa-bars m-1"></i>
        <i class="fa-solid fa-user avatar m-1"></i>
      </button>
      <ul class="dropdown-menu dropdown-menu-end mt-2 shadow p-2 mb-5 bg-body rounded" aria-labelledby="dropdownMenuButton1">
        <% if user_signed_in? %>
          <li>
            <%= link_to "Airbnb your home", new_flat_path, class: "dropdown-item", data: {turbo: false} %>
            <%= link_to "Manage bookings", user_path(current_user), class:"dropdown-item" %>
          </li>

          <li><hr class="dropdown-divider"></li>

          <li>
            <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
          </li>
        <% else %>
          <li>
          <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
          </li>

          <li><hr class="dropdown-divider"></li>

          <li>
          <%= link_to "Log In", new_user_session_path, class: "dropdown-item" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get">
  <div class="search-form-control" id="search-form">
    <input class="form-control string required" type="text" name="search_query" id="search_query" />
    <button type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
</form>

app/views/users/show.html.erb
<p></p>
<h1>Welcome, <%= @user.name %>!</h1>

<p></p>
<p>My listing(s)</p>
<div class="cards-container">
  <% @user.flats.each do |flat| %>
    <div class="card-product">
      <% if flat.photo.attached?%>
        <%= cl_image_tag flat.photo.key, class: "card-product-infos" %>
        <% else %>
        <%= image_tag "https://t3.ftcdn.net/jpg/04/62/93/66/360_F_462936689_BpEEcxfgMuYPfTaIAOC1tCDurmsno7Sp.jpg" %>
      <% end %>
      <div class="card-product-infos">
        <h2><%= link_to flat.name, flat_path(flat.id), class: "link" %> at <%= flat.location %></h2>
        <p><%= link_to "Edit", edit_flat_path(flat.id) %></p>
      </div>
    </div>
    <%end%>
</div>

<p></p>
<p>Manage guest reservation(s)</p>
<div class="cards-container">
<% @user.flats.order("created_at").each do |flat| %>
  <%flat.bookings.each do |booking|%>
  <div class="card-product">
      <% if flat.photo.attached?%>
        <%= cl_image_tag flat.photo.key, class: "card-product-infos" %>
        <% else %>
        <%= image_tag "https://t3.ftcdn.net/jpg/04/62/93/66/360_F_462936689_BpEEcxfgMuYPfTaIAOC1tCDurmsno7Sp.jpg" %>
      <% end %>
      <div class="card-product-infos">
        <div data-controller="check-box">
        <input type = "checkbox" id ="status-box" data-action="click->check-box#check" data-check-box-target="box">
        <label for="status" id="status-text">
            <% if booking.accepted == true %>
            Accepted
            <% else %>
            Not Accepted
            <%end%>
        </label>
        </div>
      <p></p>
      <h2><%= flat.name %> at <%= flat.location %></h2>
      <p>Booked by <strong><%= booking.customer.name %></strong> from <%= booking.start_date %> to <%= booking.end_date %></p>
    </div>
  </div>
      <% end %>
  <% end %>
</div>

<p></p>
<p>My reservation(s)</p>
<div class="cards-container">
<% @user.bookings.order("start_date").each do |booking| %>
  <div class="card-product">
    <% if booking.flat.photo.attached?%>
      <%= cl_image_tag booking.flat.photo.key, class: "card-product-infos" %>
      <% else %>
      <%= image_tag "https://t3.ftcdn.net/jpg/04/62/93/66/360_F_462936689_BpEEcxfgMuYPfTaIAOC1tCDurmsno7Sp.jpg" %>
    <% end %>
  <div class="card-product-infos">
    <h2><%= booking.flat.name %> at <%= booking.flat.location %></h2>
    <p><strong>From </strong><%= booking.start_date %><strong> to </strong><%= booking.end_date %></p></p>
    </div>
  </div>
  <%end%>
</div>